#==============================================================
# Debug mode
#==============================================================
localhost: http://localhost:3000
debug : true
debug : false


#==============================================================
# Maintain mode
#==============================================================
maintain : false
# maintain : true


#==============================================================
# Administator info
#==============================================================
admin_name: 產生器製造機
admin_email: hi@gengen.co


#==============================================================
# Site settings
#==============================================================
site_name         : 產生器製造機⚡Generator Generator
site_title        : 產生器製造機⚡
site_description  : 眾人引頸期盼的「產生器製造機⚡」橫空出世，讓愛卿不需要耗費洪荒之力，就能免費、快速建立各種有趣實用的圖像產生器
site_url          : https://gengen.co
site_version      : 1.72.99

og_type           : website
og_image          : https://gengen.co/images/og-image.jpg
ga_track_id       : UA-124037846-1


#==============================================================
# Build exclude
#==============================================================
exclude:
  - gulpfile.js
  - package.json
  - node_modules
  - assets


#==============================================================
# Html compress config
#==============================================================
compress_html:
  clippings: all


#==============================================================
# Jekyll setting
#==============================================================
destination: public
