en =
  site:
    title: 'Generator Generator⚡'
    description: 'Create interesting and useful generators in minutes'

  template:
    avatar: 'Avatar generator'
    sticker: 'Sticker generator'
    subtitle: 'Subtitle generator'
    quote: 'Quote generator'
    cover: 'Cover generator'
    meme: 'Meme generator'

  hero:
    slogan: 'Create interesting and useful generators in minutes'
    introduce: 'Here comes the Generator Generator⚡! It will let you create interesting and useful generator in minutes. We have provided a variety of templates, and continuously adding more. It’s time to play with your creativity!'

  nav:
    home: 'Home'
    login: 'Login'
    logout: 'Logout'
    create: 'Create Generator'
    generator_list: 'List of Generators'
    newest_list: 'Newest Generators'
    popular_list: 'Most Popular Generators'
    most_used_list: 'Most Used Generators'
    official_list: 'Official Generators'
    official: 'Official Generators'
    faq: 'FAQ'
    privacy: 'Privacy Policy'
    terms: 'Terms of Use'
    feed: 'Feed'
    feed_home: 'Feed'
    user_account: 'Account'
    user_generators: 'My Generators'
    edit_generator: 'Edit Generator'
    user_posts: 'My Posts'
    user_photos: 'My Photos'
    user_links: 'My Links'

  title:
    admin_recommend: 'Recommended'
    choose_template: 'Choose Generator Type'
    basic_information: 'Basic Informations'
    upload_cover: 'Upload Cover'
    create_generator: 'Create Generator'
    more_generators: 'More Generators'
    danger_zone: 'Danger Zone'
    generator_setting: 'Generator Settings'
    basic_setting: 'Basic Settings'
    creator_setting: 'Creator Settings'
    human_verify: 'Human Verify'
    delete_confirm: 'Delete It?'
    delete_success: 'Delete Success!'
    share_generator: 'Share Generator'
    edit_image: 'Edit Image'
    choose_frame: 'Choose Frame'
    choose_sticker: 'Choose Sticker'
    upload_image: 'Upload Image'
    design_subtitle: 'Made Up Convo'
    choose_background_image: 'Choose Background Image'
    text_size: 'Text Size'
    quote_text: 'Quote Content'
    role_name: 'Signature'
    choose_role_image: 'Choose Role Image'
    login_account: 'Log in to your account'
    share: 'Share'
    generator_feed: '\'s Feed'
    information: 'Information'
    user_submissions: 'Generator Feed'
    language: 'Language'
    generators: 'Generators'
    about: 'About'
    follow_us: 'Follow Us'
    report_reason: 'What\'s Wrong With This Page?'
    sponsor_us: 'Sponsor Us'
    content_text: 'Text'
    choose_font: 'Choose Font'
    vertical_text: 'Vertical Text'
    text_align: 'Text Align'
    text_position: 'Text Position'
    choose_meme_image: 'Choose Meme Image'

  text:
    hello: 'Hello World!'
    empty_list: 'No result.'
    generator: 'Generator'
    public: 'Public'
    unlist: 'Unlist'
    default_cover: 'Use default image'
    custom_cover: 'Upload image'
    drag_file_here: 'Drop your file'
    whos_generator: '\'s generators'
    anonymous: 'Anonymous'
    search: 'Search'
    go_back: 'Return to '
    new: 'NEW'
    hot: 'HOT'
    fun: 'FUN'
    play: 'PLAY →'
    personally_created_images: 'Personally created picture'
    cc_license_images: 'Creative commons license images'
    legally_authorized_images: 'Legally authorized by images owner'
    other_copyright_state: 'Other (please explain)'
    generator_url: 'Generator link'
    btc_donate: 'BTC Donate'
    eth_donate: 'ETH Donate'
    show_more: 'show more'
    show_less: 'show less'
    poem_syllable: 'Length'
    acrostic_position: 'Position'
    wujue: 'Wujue'
    qijue: 'Qijue'
    see_example: 'See example'
    top: 'Top'
    bottom: 'Bottom'

  label:
    generator_title: 'Generator Title'
    generator_description: 'Generator Description'
    event_information: 'Event Information (optional)'
    tags: 'Tag (optional)'
    generator_privacy: 'Privacy Settings'
    generator_cover: 'Generator Cover Image'
    background_color: 'Background color'
    text_color: 'Text color'
    upload_frame_image: 'Upload frame images'
    upload_example_image: 'Upload example image'
    upload_sticker_image: 'Upload sticker images'
    upload_role_image: 'Upload role images'
    default_quote: 'Default text'
    role_name: 'Role signature'
    upload_basemap_image: 'Upload basemap images'
    upload_meme_image: 'Upload meme images'
    default_text: 'Default text'
    top_text: 'Top meme text (optional)'
    bottom_text: 'Bottom meme text'
    delete_this_generator: 'Delete this generator'
    generator_template: 'Generator Template'
    user_name: 'User Name'
    user_avatar: 'Avatar'
    creator_name: 'Creator Display Name'
    multiple_language: 'Enable multiple languages'
    choose_multiple_language: 'Please select additional languages'
    yes: 'Yes'
    no: 'No'
    image_copyright: 'Image source and copyright'
    image_copyright_notice: 'Image copyright notice and source link'
    set_sticker_position: 'Set sticker default position'
    align_center: 'Center'
    align_left: 'Left'
    align_right: 'Right'

  message:
    generator_title: 'For example: Trump generator. Max length: 30 characters.'
    generator_description: 'Please enter a short introduction to the generator. Max length: 100 characters.'
    event_information: 'Please enter relevant event information. Support Markdown syntax.'
    tags: 'Please separate by space.'
    delete_generator: 'Once you delete a generator, there is no going back. Please be certain.'
    delete_success_content: 'And can not recover anymore.'
    mobile_save_image_tip: 'Please long press on the image and save the image.'
    your_email: 'Your email'
    your_message: 'Your message'
    sticker_images: 'Please upload PNG format images with transparent background.'
    sticker_example_image: 'Please upload a JPG image, the recommended size is 900x600 pixels.'
    avatar_frame_images: 'Please upload PNG format images with a transparent background of 600x600 pixels.'
    avatar_example_image: 'Please upload a JPG image with a size of 600x600 pixels.'
    cover_frame_images: 'Please upload PNG format images with a transparent background of 850x315 pixels.'
    cover_example_image: 'Please upload a JPG image with a size of 850x315 pixels.'
    role_images: 'Please upload JPG or PNG format images with a size of 254x315 pixels.'
    quote_default_text: 'Please enter a quote.'
    role_name: 'Please enter the source or author name.'
    subtitle_basemap_images: 'Please upload JPG or PNG format images with a recommended size of 640x480 pixels.'
    subtitle_default_text: 'Please enter the default made up convo text.'
    meme_meme_images: 'Please upload PNG or JPG format images.'
    meme_top_text: 'Max length: 200 characters.'
    meme_bottom_text: 'Max length: 200 characters.'
    multiple_language: 'With the generator multi-language option enabled, you can fill in the title and description separately for each language.'
    user_photos_warning: 'Note: The images below are images that you have recently generated using the generators. They are only stored on the device you are currently using and cannot be accessed across devices.'
    user_links_warning: 'Note: The links below are images that you have recently generated using the generators. They are only stored on the device you are currently using and cannot be accessed across devices.'
    comment_placeholder: 'Add a public comment...'
    write_something: 'Say something about this...'
    your_are_human: 'You are Human!'
    image_copyright: 'The source and copyright of the image material you will use in this generator'
    image_copyright_notice: 'If the copyright owner requests to indicate the source, please enter the copyright information and link in this field.'
    report_issue: 'Help us understand what\'s happening';
    comment_message: 'Max length: 1000 characters.'
    sponsor_message: 'If you like our platform you can sponsor in the following ways:'
    poem_text: 'Chinese characters only, word limit 10 words.'
    inscribed_board_text: 'Chinese characters only, word limit 4 words.'
    open_in_browser: 'Please visit this page from your browser APP.'

  validation:
    generator_title: 'Required. Max length: 30 characters'
    generator_description: 'Required. Max length: 100 characters'

  button:
    agree: 'Agree'
    disagree: 'Disagree'
    preview_generator: 'Preview generator'
    continue_edit: 'Continue edit'
    create_generator: 'Create generator'
    create: 'Create'
    show_more: 'Show more'
    download_image: 'Download'
    create_link: 'Generate link'
    more_action: 'More'
    previous_step: 'Previous'
    next_step: 'Next'
    view_list: 'View list'
    edit_generator: 'Edit'
    delete_generator: 'Delete generator'
    update: 'Save changes'
    cancel: 'Cancel'
    done: 'Done'
    close: 'Close'
    yes_delete: 'Yes, delete it'
    send: 'Send'
    crop_image: 'Crop image'
    filter_effect: 'Filter effect'
    merge_image: 'Merge images'
    choose_image: 'Upload photo'
    load_my_avatar: 'Use my avatar'
    share_to_feed: 'Post to Feed'
    google_login: 'Log in with Google'
    github_login: 'Log in with Github'
    twitter_login: 'Log in with Twitter'
    facebook_login: 'Log in with Facebook'
    use_this_image: 'Use this photo'
    use_generator: 'Use generator'
    share_to_facebook: 'Share to Facebook'
    share_to_twitter: 'Share to Twitter'
    share_to_googleplus: 'Share to Google+'
    share_to_line: 'Share to Line'
    comment: 'Comment'
    go_back_feed: 'Return to Feed'
    copy: 'Copy'
    click_copy: 'Click to Copy'
    continue: 'Continue'
    delete_post: 'Delete post'
    report: 'Report'
    generate_poem: 'Generate'

  alert:
    generator_title_empty: 'Please fill in the generator title.'
    generator_description_empty: 'Please fill in the generator description.'
    generator_cover_empty: 'Please upload a cover image.'
    frame_image_empty: 'Please upload frame images.'
    example_image_empty: 'Please upload example image.'
    sticker_image_empty: 'Please upload sticker images.'
    basemap_image_empty: 'Please upload basemap images.'
    default_text_empty: 'Please fill in the default text.'
    role_image_empty: 'Please upload role images.'
    role_name_empty: 'Please fill in the role signature.'
    generator_create_failed: 'Generator creation failed, please try again later.'
    merge_success: 'Image synthesis succeeded.'
    verify_failed: 'Verification failed, please try again later.'
    setting_updated: 'Thank you, your settings have been saved.'
    something_went_wrong: 'Oops, something went wrong! Please try to refresh the page or try again later.'
    local_preview_failed: 'Failed to loading preview image.'
    image_upload_failed: 'Image upload failed, please try again later.'
    link_generating: 'Image link is generating, please wait...'
    link_generate_failed: 'Oops, image link create failed, please try again later.'
    login_failed: 'Login failed, please try to refresh the page or try again later.'
    logout_failed: 'Logout failed, please try to refresh the page or try again later.'
    list_loading_failed: 'List failed to load, please try to refresh.'
    no_more_data: 'This is the last page.'
    delete_success: 'Successfully deleted!'
    delete_failed: 'Oops, deletion failed, please try again later!'
    processing: 'Processing...'
    report_success: 'Thanks for your report.'

  user_terms:
    title: 'Terms of Use'
    content: 'content'

  time:
    years_ago: ' years'
    months_ago: ' months'
    days_ago: ' days'
    hours_ago: ' hrs'
    mins_ago: 'min'
    just_now: 'Just now'

  tooltip:
    set_as_default: 'Set as default'
    crop_image: 'Crop'
    remove_item: 'Remove'

  report:
    reason_1: 'I just don\'t like it'
    reason_2: 'It\'s harassing me or someone I know'
    reason_3: 'I think it shouldn\'t be on gengen.co'
    reason_4: 'It\'s a scam'
    reason_5: 'I think it\'s an unauthorized use of my intellectual property'
    reason_6: 'Other (please explain)'
