ja =
  site:
    title: 'ジェネレータージェネレーター⚡'
    description: '楽しく便利なイメージジェネレーターをすばやく作成できます'

  template:
    avatar: 'プロフィール画像'
    sticker: 'ステッカー'
    subtitle: '字幕画像'
    quote: '名言画像'
    cover: 'カバー画像'
    meme: 'ミーム'

  hero:
    slogan: '数分で面白くて便利なジェネレーターを生成する'
    introduce: 'ここに「ジェネレータージェネレーター⚡」が来る！それはあなたが分で興味深いと便利なジェネレーターを作成させることができます。 私たちはバラエティーなテンプレートを提供し続けています。 あなたの創造力で遊ぶ時間です！'

  nav:
    home: 'ホーム'
    login: 'ログイン'
    logout: 'ログアウト'
    create: 'ジェネレーターを作る'
    generator_list: 'ジェネレーターリスト'
    newest_list: '最新のジェネレーター'
    popular_list: '人気ジェネレーター'
    most_used_list: '人々最も利用している'
    official_list: '公式ジェネレーター'
    official: '公式ジェネレーター'
    faq: 'よくあるご質問'
    privacy: 'プライバシーポリシー'
    terms: '利用規約'
    feed: 'フィード'
    feed_home: 'フィード'
    user_account: 'アカウント'
    user_generators: '私のジェネレーター'
    edit_generator: 'ジェネレータの編集'
    user_posts: '私のポスト'
    user_photos: '私のポートフォリオ'
    user_links: '私のリンク'

  title:
    admin_recommend: 'おすすめ'
    choose_template: 'テンプレートを選択'
    basic_information: '基本情報'
    upload_cover: 'カバーをアップロード'
    create_generator: 'ジェネレーターを作る'
    more_generators: 'もっと多くのジェネレーター'
    danger_zone: '危険区域'
    generator_setting: 'ジェネレーターの設定'
    basic_setting: '基本設定'
    creator_setting: 'クリエイターの設定'
    human_verify: '人間とロボットの検証'
    delete_confirm: '消して？'
    delete_success: '削除成功！'
    share_generator: 'シェア'
    edit_image: '画像編集'
    choose_frame: 'フレームを選択'
    choose_sticker: 'ステッカーを選択'
    upload_image: '画像をアップロード'
    design_subtitle: 'ボケテキスト'
    choose_background_image: '背景画像を選択'
    text_size: '文字サイズ'
    quote_text: 'テキスト'
    role_name: '署名'
    choose_role_image: 'ロールイメージを選択'
    login_account: 'ログイン'
    share: 'シェア'
    generator_feed: 'のフィード'
    information: '写真の詳細'
    user_submissions: 'ユーザーの投稿'
    language: '言語'
    generators: 'ジェネレーター'
    about: '概要'
    follow_us: 'フォローする'
    report_reason: 'このページを報告する理由'
    sponsor_us: 'スポンサー'
    content_text: 'テキスト'
    choose_font: 'フォントを選択'
    vertical_text: '縦書き'
    text_align: '文字揃え'
    text_position: 'テキストの位置'
    choose_meme_image: 'ミームイメージを選択'

  text:
    empty_list: '検索結果はありません'
    generator: 'ジェネレーター'
    public: '公開'
    unlist: '非公開'
    default_cover: 'プリセット画像を使用する'
    custom_cover: '画像をアップロードする'
    drag_file_here: 'アップロード'
    whos_generator: 'のジェネレーター'
    anonymous: 'アノニマス'
    search: '検索'
    go_back: '返る'
    new: '新しい'
    hot: 'ホット'
    fun: '楽しい'
    play: '遊びます →'
    personally_created_images: '個人的に作成された画像'
    cc_license_images: 'CCライセンスの画像'
    legally_authorized_images: '画像の所有者によって合法的に承認された'
    other_copyright_state: 'その他（説明してください）'
    generator_url: 'ジェネレーターのリンク'
    btc_donate: 'ビットコイン寄付'
    eth_donate: 'エテリアム寄付'
    show_more: 'もっと見る'
    show_less: '一部を表示'
    poem_syllable: '各句の長さ'
    acrostic_position: '隠れた字の位置'
    wujue: '五言'
    qijue: '七言'
    see_example: '例を参照してください'
    top: '上'
    bottom: '下'

  label:
    generator_title: 'タイトル'
    generator_description: 'ジェネレーターの説明'
    event_information: '活動メッセージ（オプション）'
    tags: 'タグ（オプション）'
    generator_privacy: 'プライバシー設定'
    generator_cover: 'ジェネレーターカバー画像'
    background_color: '背景色を選択'
    text_color: 'テキストの色を選択'
    upload_frame_image: 'フレーム画像をアップロードする'
    upload_example_image: 'サンプル画像をアップロードする'
    upload_sticker_image: 'ステッカーイメージをアップロードする'
    upload_role_image: 'ロールイメージをアップロードする'
    default_quote: 'デフォルトのテキスト'
    role_name: '署名'
    upload_basemap_image: '底図をアップロードする'
    upload_meme_image: 'ミームイメージをアップロードする'
    default_text: 'デフォルトテキスト'
    top_text: 'トップテキスト（オプション）'
    bottom_text: 'ボトムテキスト'
    delete_this_generator: 'このジェネレーターを削除する'
    generator_template: 'ジェネレーターテンプレート'
    user_name: 'ユーザー名'
    user_avatar: 'アバター'
    creator_name: 'クリエイターの表示名'
    multiple_language: '複数の言語を有効にする'
    choose_multiple_language: '追加の言語を選択してください'
    yes: 'はい'
    no: 'いいえ'
    image_copyright: '画像ソースと著作権'
    image_copyright_notice: '画像著作権表示とソースリンク'
    set_sticker_position: 'ステッカーの初期位置を設定する'
    align_center: '中央揃え'
    align_left: '左揃え'
    align_right: '右揃え'

  message:
    generator_title: '最大長は30文字です。例：トランプジェネレーター。'
    generator_description: 'ジェネレーターの説明を記入してください。最大長は100文字です。'
    event_information: '関連する活動情報を入力してください。Markdown構文をサポート。'
    tags: 'スペースで区切ってください。'
    delete_generator: 'ジェネレーターを削除すると、元に戻りません。 ご確認ください。'
    delete_success_content: 'もう回復できない。'
    mobile_save_image_tip: '画像を長押しして画像を保存してください'
    your_email: 'あなたの電子メール'
    your_message: 'あなたのメッセージ'
    sticker_images: '背景が透明なPNG形式の画像をアップロードしてください。'
    sticker_example_image: 'JPGイメージをアップロードしてください。推奨サイズは900x600ピクセルです。'
    avatar_frame_images: 'サイズが600x600ピクセルの透明な背景を持つPNG形式の画像をアップロードします。'
    avatar_example_image: 'サイズが600x600ピクセルのJPG画像をアップロードしてください。'
    cover_frame_images: 'サイズが850x315ピクセルの透明な背景を持つPNG形式の画像をアップロードします。'
    cover_example_image: 'サイズが850x315ピクセルのJPG画像をアップロードしてください。'
    role_images: 'サイズが254x315ピクセルのJPGまたはPNG形式の画像をアップロードしてください。'
    quote_default_text: 'デフォルトテキストを入力してください。'
    role_name: '署名を書き留めてください。'
    subtitle_basemap_images: '推奨サイズ640x480ピクセルのJPGまたはPNG形式の画像をアップロードしてください。'
    subtitle_default_text: 'デフォルトテキストを入力してください。'
    meme_meme_images: 'JPGまたはPNG形式の画像'
    meme_top_text: '最大長は200文字です。'
    meme_bottom_text: '最大長は200文字です。'
    multiple_language: 'ジェネレーターの多言語オプションを有効にすると、言語ごとにタイトルと説明を個別に記入することができます。'
    user_photos_warning: '注：以下の画像は、最近ジェネレーターを使用して生成した画像です。現在使用しているデバイスにのみ保存され、デバイス間ではアクセスできません。'
    user_links_warning: '注：以下のリンクは、最近ジェネレーターを使用して生成した画像です。現在使用しているデバイスにのみ保存され、デバイス間ではアクセスできません。'
    comment_placeholder: '公開コメントを追加...'
    write_something: '何か書く…'
    your_are_human: 'あなたは人間です！'
    image_copyright: 'このジェネレータで使用する画像素材のソースと著作権'
    image_copyright_notice: '著作権者が情報源の提示を要求した場合は、このフィールドに著作権情報とリンクを入力してください'
    report_issue: '問題の内容についてお聞かせください'
    comment_message: '最大長は1000文字です。'
    sponsor_message: '私たちのプラットフォームが好きなら、あなたは次の方法で私たちをスポンサーできます。'
    poem_text: '漢字のみ、単語の制限は10語'
    inscribed_board_text: '漢字のみ、単語の制限は4語'
    open_in_browser: 'あなたのブラウザアプリからこのページをご覧ください。'

  validation:
    generator_title: '必須，最大長は30文字です。'
    generator_description: '必須，最大長は100文字です。'

  button:
    agree: '同意する'
    disagree: '同意しない'
    preview_generator: 'プレビュージェネレーター'
    continue_edit: '編集を続ける'
    create_generator: 'ジェネレーターを作る'
    create: '生成する'
    show_more: 'もっと見る'
    download_image: 'ダウンロード'
    create_link: 'リンク生成'
    more_action: 'もっと'
    previous_step: '前へ'
    next_step: '次へ'
    view_list: '一覧を見る'
    edit_generator: '編集する'
    delete_generator: 'ジェネレーターを削除'
    update: '変更を保存'
    cancel: 'キャンセル'
    done: '編集が完了しました'
    close: '閉じる'
    yes_delete: 'はい、削除してください'
    send: 'メールを送る'
    crop_image: 'クロップ画像'
    filter_effect: 'フィルター効果'
    merge_image: 'イメージをマージする'
    choose_image: 'ファイルを選ぶ'
    load_my_avatar: 'アバターを使う'
    share_to_feed: '投稿'
    google_login: 'Google でログイン'
    github_login: 'Github でログイン'
    twitter_login: 'Twitter でログイン'
    facebook_login: 'Facebook でログイン'
    use_this_image: '使用する'
    use_generator: '使用する'
    share_to_facebook: 'Facebook にシェア'
    share_to_twitter: 'Twitter にシェア'
    share_to_googleplus: 'Google+ にシェア'
    share_to_line: 'Line にシェア'
    comment: 'コメント'
    go_back_feed: 'フィードに戻る'
    copy: 'コピー'
    click_copy: 'クリックしてコピーする'
    continue: '続ける'
    delete_post: '投稿を削除'
    report: '報告'
    generate_poem: '詩を書く'

  alert:
    generator_title_empty: 'タイトルを記入してください。'
    generator_description_empty: 'ジェネレーターの説明を記入してください。'
    generator_cover_empty: '表紙画像をアップロードしてください'
    frame_image_empty: 'フレーム画像をアップロードしてください。'
    example_image_empty: 'サンプル画像をアップロードしてください。'
    sticker_image_empty: 'ステッカー画像をアップロードしてください。'
    basemap_image_empty: 'ベースマップ画像をアップロードしてください。'
    default_text_empty: 'デフォルトのテキストを入力してください。'
    role_image_empty: 'キャラクター画像をアップロードしてください'
    role_name_empty: 'キャラクターの署名を記入してください。'
    generator_create_failed: '発電機の作成に失敗しました。後でもう一度お試しください。'
    merge_success: '画像合成に成功しました。'
    verify_failed: 'キャプチャ認証に失敗しました。後でもう一度お試しください。'
    setting_updated: '設定を保存しました。'
    something_went_wrong: 'おっと！何かが間違っていた！ ページを更新するか、後でやり直してください。'
    local_preview_failed: 'プレビュー画像の読み込みに失敗しました。'
    image_upload_failed: '画像のアップロードに失敗しました。後でもう一度お試しください。'
    link_generating: 'リンクが生成されています、お待ちください...'
    link_generate_failed: 'リンク生成に失敗しました。しばらくしてからもう一度お試しください。'
    login_failed: 'ログインに失敗しました。ページを更新するか、後でやり直してください。'
    logout_failed: 'ログアウトに失敗しました。ページを更新するか、後でやり直してください。'
    list_loading_failed: 'リストの読み込みに失敗しました。リフレッシュしてください。'
    no_more_data: '最後のページ'
    delete_success: '削除されました！'
    delete_failed: 'おっと！ 削除に失敗しました。しばらくしてからもう一度お試しください！'
    processing: '処理中にお待ちください。'
    report_success: '報告ありがとうございます。'

  user_terms:
    title: '利用規約'
    content: 'content'

  time:
    years_ago: '年前'
    months_ago: 'ヶ月前'
    days_ago: ' 日前'
    hours_ago: '時間前'
    mins_ago: '分前'
    just_now: '数秒前'

  tooltip:
    set_as_default: '預設'
    crop_image: 'クロップ'
    remove_item: '削除'

  report:
    reason_1: '気に入らない'
    reason_2: '私または知り合いに対する嫌がらせである'
    reason_3: 'gengen.coに載せるべきではないと思う'
    reason_4: '詐欺コンテンツである'
    reason_5: '私の著作物を無許可で使用していると思う'
    reason_6: 'その他（説明してください）'
