zh_hant =
  site:
    title: '產生器製造機⚡'
    description: '眾人引頸期盼的「產生器製造機⚡」橫空出世，讓您不需要耗費洪荒之力，就能免費、快速建立各種有趣實用的圖像產生器'

  template:
    avatar: '頭像產生器'
    sticker: '貼紙產生器'
    subtitle: '設計對白產生器'
    quote: '名言圖產生器'
    cover: '封面產生器'
    meme: '迷因產生器'

  hero:
    slogan: '彈指間快速建立有趣實用的產生器'
    introduce: '眾人引頸期盼的「產生器製造機⚡」來啦！讓您不需要耗費洪荒之力，就能快速建立各種有趣實用的圖像產生器。我們提供了數種產生器樣板，並且持續增加中，讓您可以自由揮灑創意！'

  nav:
    home: 'Home'
    login: '登入'
    logout: '登出'
    create: '製作產生器'
    generator_list: '產生器列表'
    newest_list: '最新上線'
    popular_list: '熱門產生器'
    most_used_list: '最多人玩過'
    official_list: '官方出品'
    official: '官方出品產生器'
    faq: '常見問題'
    privacy: '隱私權政策'
    terms: '使用條款'
    feed: '動態'
    feed_home: '動態'
    user_account: '帳戶'
    user_generators: '我的產生器'
    edit_generator: '編輯產生器'
    user_posts: '我的發文'
    user_photos: '我的圖片'
    user_links: '我的連結'

  title:
    admin_recommend: '站長推薦'
    choose_template: '選擇產生器類型'
    basic_information: '基本資料'
    upload_cover: '上傳封面圖片'
    create_generator: '製作產生器'
    more_generators: '更多產生器'
    danger_zone: '危險區域'
    generator_setting: '產生器設定'
    basic_setting: '基本設定'
    creator_setting: '創作者設定'
    human_verify: '人類驗證'
    delete_confirm: '確定要刪除嗎？'
    delete_success: '刪除成功！'
    share_generator: '分享產生器'
    edit_image: '編輯底圖'
    choose_frame: '選擇圖框'
    choose_sticker: '選擇合成貼紙'
    upload_image: '上傳圖片'
    design_subtitle: '設計對白'
    choose_background_image: '選擇背景圖'
    text_size: '文字大小'
    quote_text: '名言內容'
    role_name: '署名'
    choose_role_image: '選擇角色圖片'
    login_account: '登入您的帳戶'
    share: '分享'
    generator_feed: '的動態'
    information: '資訊'
    user_submissions: '網友投稿'
    language: '語言'
    generators: '產生器'
    about: '關於'
    follow_us: '追蹤我們'
    report_reason: '這個頁面有什麼問題？'
    sponsor_us: '贊助我們'
    content_text: '內容文字'
    choose_font: '選擇字體'
    vertical_text: '直書文字'
    text_align: '文字對齊方向'
    text_position: '文字位置'
    choose_meme_image: '選擇迷因圖'

  text:
    empty_list: '沒有內容'
    generator: '產生器'
    public: '公開'
    unlist: '非公開'
    default_cover: '預設封面'
    custom_cover: '自行上傳封面圖片'
    drag_file_here: '上傳檔案'
    whos_generator: ' 製作的產生器'
    anonymous: '匿名'
    search: '搜尋'
    go_back: '返回'
    new: '最新'
    hot: '熱門'
    fun: '好玩'
    play: '來去玩玩 →'
    personally_created_images: '本人創作或拍攝之圖像'
    cc_license_images: '創用CC授權之圖像'
    legally_authorized_images: '由擁有者合法授權使用之圖像'
    other_copyright_state: '其他（請說明）'
    generator_url: '產生器網址'
    btc_donate: 'BTC贊助'
    eth_donate: 'ETH贊助'
    show_more: '顯示更多'
    show_less: '顯示較少'
    poem_syllable: '每句長度'
    acrostic_position: '藏頭位置'
    wujue: '五言'
    qijue: '七言'
    see_example: '查看範例'
    top: '上'
    bottom: '下'

  label:
    generator_title: '產生器名稱'
    generator_description: '產生器簡介'
    event_information: '活動訊息（選填）'
    tags: '標籤（選填）'
    generator_privacy: '是否公開產生器'
    generator_cover: '產生器封面'
    background_color: '選擇背景顏色'
    text_color: '選擇文字顏色'
    upload_frame_image: '上傳特效框圖片'
    upload_example_image: '上傳範例底圖'
    upload_sticker_image: '上傳貼紙圖片'
    upload_role_image: '上傳角色圖片'
    default_quote: '預設名言'
    role_name: '署名'
    upload_basemap_image: '上傳底圖'
    upload_meme_image: '上傳迷因圖'
    default_text: '預設文字'
    top_text: '上方文字（選填）'
    bottom_text: '下方文字'
    delete_this_generator: '刪除這個產生器'
    generator_template: '產生器樣板'
    user_name: '用戶名稱'
    user_avatar: '用戶頭像'
    creator_name: '創作者顯示名稱'
    multiple_language: '啟用多語言'
    choose_multiple_language: '請選擇語言'
    yes: '是'
    no: '否'
    image_copyright: '圖像來源及版權'
    image_copyright_notice: '圖像版權聲明及來源連結'
    set_sticker_position: '設定貼紙初始位置'
    align_center: '置中'
    align_left: '置左'
    align_right: '置右'

  message:
    generator_title: '字數限制 30 字，例如：柯P跌倒產生器'
    generator_description: '請輸入產生器的簡短介紹，字數限制 100 字'
    event_information: '請輸入相關活動訊息，支援 Markdown 語法'
    tags: '請以空格隔開'
    delete_generator: '產生器刪除後無法被復原，刪除前請三思'
    delete_success_content: '刪掉啦！再也無法復原啦！'
    mobile_save_image_tip: '請在圖片上長按以下載圖片'
    your_email: '你的Email'
    your_message: '請輸入訊息'
    sticker_images: '請上傳透明背景之PNG格式圖片'
    sticker_example_image: '請上傳JPG格式圖片，建議尺寸900x600像素'
    avatar_frame_images: '請上傳透明背景之PNG格式圖片，尺寸為600x600像素'
    avatar_example_image: '請上傳JPG格式圖片，尺寸為600x600像素'
    cover_frame_images: '請上傳透明背景之PNG格式圖片，尺寸為850x315像素'
    cover_example_image: '請上傳JPG格式圖片，尺寸為850x315像素'
    role_images: '請上傳JPG或PNG格式圖片，尺寸為254x315像素'
    quote_default_text: '請輸入名言內容'
    role_name: '請輸入名言作者之署名'
    subtitle_basemap_images: '請上傳JPG或PNG格式圖片，建議尺寸640x480像素'
    subtitle_default_text: '請輸入預設設計對白'
    meme_images: '請上傳JPG或PNG格式圖片'
    meme_top_text: '字數限制 200 字'
    meme_bottom_text: '字數限制 200 字'
    multiple_language: '針對不同語言分別填寫標題和簡介內容'
    user_photos_warning: '注意：以下圖片為您近期使用產生器產生的圖片，僅儲存於您目前使用的裝置，無法跨裝置取用'
    user_links_warning: '注意：以下連結為您近期使用產生器產生的連結，僅儲存於您目前使用的裝置，無法跨裝置取用'
    comment_placeholder: '新增公開留言...'
    write_something: '留個話吧⋯⋯'
    your_are_human: '你是人類！'
    image_copyright: '您將使用於本產生器之圖像素材來源及版權'
    image_copyright_notice: '如圖像版權方要求於利用該圖片素材需「註明出處」時，請將版權資訊和連結填寫於本欄位'
    report_issue: '協助我們瞭解發生的狀況'
    comment_message: '字數限制 1000 字'
    sponsor_message: '如果你喜歡我們平台可以用以下方式贊助：'
    poem_text: '僅限中文字，字數限制 10 字'
    inscribed_board_text: '僅限中文字，字數限制 4 字'
    open_in_browser: '請使用瀏覽器APP開啟本頁面'

  validation:
    generator_title: '必填，且字數限制為 30 字以內'
    generator_description: '必填，且字數限制為 100 字以內'

  button:
    agree: '同意'
    disagree: '不同意'
    preview_generator: '預覽產生器'
    continue_edit: '繼續編輯'
    create_generator: '製作產生器'
    create: '完成'
    show_more: '顯示更多'
    download_image: '下載圖片'
    create_link: '產生連結'
    more_action: '更多'
    previous_step: '上一步'
    next_step: '下一步'
    view_list: '查看列表'
    edit_generator: '編輯'
    delete_generator: '刪除產生器'
    update: '儲存變更'
    cancel: '取消'
    done: '完成'
    close: '關閉'
    yes_delete: '是的，刪了它！'
    send: '發送'
    crop_image: '裁切'
    filter_effect: '濾鏡效果'
    merge_image: '合併到底圖'
    choose_image: '上傳圖片'
    load_my_avatar: '載入頭像'
    share_to_feed: '投稿'
    google_login: '以 Google 帳戶登入'
    github_login: '以 Github 帳戶登入'
    twitter_login: '以 Twitter 帳戶登入'
    facebook_login: '以 Facebook 帳戶登入'
    use_this_image: '使用這張'
    use_generator: '使用產生器'
    share_to_facebook: '分享到 Facebook'
    share_to_twitter: '分享到 Twitter'
    share_to_googleplus: '分享到 Google+'
    share_to_line: '分享到 Line'
    comment: '留言'
    go_back_feed: '返回動態'
    copy: '複製'
    click_copy: '點擊以複製'
    continue: '繼續'
    delete_post: '刪除這篇發文'
    report: '檢舉'
    generate_poem: '產生詩文'

  alert:
    generator_title_empty: '請填寫產生器名稱'
    generator_description_empty: '請填寫產生器簡介'
    generator_cover_empty: '請上傳封面圖片'
    frame_image_empty: '請上傳相框圖片'
    example_image_empty: '請上傳範例圖片'
    sticker_image_empty: '請上傳貼紙圖片'
    basemap_image_empty: '請上傳底圖'
    default_text_empty: '請輸入預設文字'
    role_image_empty: '請上傳角色圖片'
    role_name_empty: '請輸入署名'
    generator_create_failed: '產生器創建失敗，請稍後再試'
    merge_success: '合上去啦！'
    verify_failed: '驗證失敗，請稍後再試'
    setting_updated: '謝謝，你的設定已儲存。'
    something_went_wrong: '糟糕，出錯了！請嘗試重新整理或稍後再試'
    local_preview_failed: '圖片預覽載入失敗！'
    image_upload_failed: '圖片上傳失敗，請稍後再試'
    link_generating: '圖片連結產生中，請稍候⋯⋯'
    link_generate_failed: '糟糕！圖片連結產生失敗，請稍後再試'
    login_failed: '登入失敗，請嘗試重新整理或稍後再試'
    logout_failed: '登出失敗，請嘗試重新整理或稍後再試'
    list_loading_failed: '列表載入失敗，請嘗試重新整理'
    no_more_data: '最後一頁了'
    delete_success: '刪除成功！'
    delete_failed: '糟糕！刪除失敗，請稍後再試！'
    processing: '處理中，請稍候⋯⋯'
    report_success: '感謝您的檢舉'

  user_terms:
    title: '使用者條款'
    content: '使用者條款內容'

  time:
    years_ago: '年前'
    months_ago: '個月前'
    days_ago: '天前'
    hours_ago: '小時前'
    mins_ago: '分鐘前'
    just_now: '現在'

  tooltip:
    set_as_default: '設為預設'
    crop_image: '裁切圖片'
    remove_item: '移除'

  report:
    reason_1: '我就是不喜歡'
    reason_2: '此內容騷擾到我或某個我認識的人'
    reason_3: '我認為這不應該出現在 gengen.co'
    reason_4: '這是詐騙'
    reason_5: '我認為這未經授權並侵犯了我的智慧財產權'
    reason_6: '其他（請說明）'
