zh_hans =
  site:
    title: '生成器製造机⚡'
    description: '横空出世的「生成器製造机⚡」，让您不需要使用洪荒之力，就能免费快速建立各种有趣实用的图像生成器'

  template:
    avatar: '头像生成器'
    sticker: '贴纸生成器'
    subtitle: '设计对白生成器'
    quote: '名言生成器'
    cover: '封面生成器'
    meme: '模因生成器'

  hero:
    slogan: '弹指间快速建立有趣实用的生成器'
    introduce: '众人引颈期盼的「生成器製造机⚡」来啦！让您不需要耗费洪荒之力，就能快速建立各种有趣实用的图像生成器。我们提供了数种产生器样板，并且持续增加中，让您可以自由挥洒创意！'

  nav:
    home: 'Home'
    login: '登入'
    logout: '登出'
    create: '制作生成器'
    generator_list: '生成器列表'
    newest_list: '最新上线'
    popular_list: '热门生成器'
    most_used_list: '最多人玩过'
    official_list: '官方出品'
    official: '官方出品生成器'
    faq: '常见问题'
    privacy: '隐私权政策'
    terms: '使用条款'
    feed: '动态'
    feed_home: '动态'
    user_account: '帐户'
    user_generators: '我的生成器'
    edit_generator: '编辑生成器'
    user_posts: '我的帖子'
    user_photos: '我的图片'
    user_links: '我的链接'

  title:
    admin_recommend: '站长推荐'
    choose_template: '选择生成器类型'
    basic_information: '基本资料'
    upload_cover: '上传封面图片'
    create_generator: '製作生成器'
    more_generators: '更多生成器'
    danger_zone: '危险区域'
    generator_setting: '產生器设置'
    basic_setting: '基本设置'
    creator_setting: '创作者设置'
    human_verify: '人类验证'
    delete_confirm: '确定要删除吗？'
    delete_success: '删除成功！'
    share_generator: '分享生成器'
    edit_image: '编辑底图'
    choose_frame: '选择图框'
    choose_sticker: '选择合成贴纸'
    upload_image: '上传图片'
    design_subtitle: '设计字幕'
    choose_background_image: '选择背景图'
    text_size: '文字大小'
    quote_text: '名言内容'
    role_name: '署名'
    choose_role_image: '选择角色图片'
    login_account: '登入您的帐户'
    share: '分享'
    generator_feed: '的动态'
    information: '信息'
    user_submissions: '网友投稿'
    language: '语言'
    generators: '生成器'
    about: '关于'
    follow_us: '追踪我们'
    report_reason: '请问该页面有什么问题？'
    sponsor_us: '赞助我们'
    content_text: '内容文字'
    choose_font: '选择字体'
    vertical_text: '直书文字'
    text_align: '文字对齐方向'
    text_position: '文字位置'
    choose_meme_image: '选择模因图'

  text:
    empty_list: '没有内容'
    generator: '生成器'
    public: '公开'
    unlist: '非公开'
    default_cover: '预设封面'
    custom_cover: '自行上传封面图片'
    drag_file_here: '上传曳档'
    whos_generator: ' 製作的生成器'
    anonymous: '匿名'
    search: '搜索'
    go_back: '返回'
    new: '新'
    hot: '热'
    fun: '趣'
    play: '玩玩 →'
    personally_created_images: '本人创作或拍摄之图像'
    cc_license_images: '创用CC授权之图像'
    legally_authorized_images: '由拥有者合法授权使用之图像'
    other_copyright_state: '其他（请说明）'
    generator_url: '生成器网址'
    btc_donate: 'BTC赞助'
    eth_donate: 'ETH赞助'
    show_more: '展示更多'
    show_less: '展示较少'
    poem_syllable: '每句长度'
    acrostic_position: '藏头位置'
    wujue: '五言'
    qijue: '七言'
    see_example: '查看示例'
    top: '上'
    bottom: '下'

  label:
    generator_title: '生成器名称'
    generator_description: '生成器简介'
    event_information: '活动讯息（选填）'
    tags: '标籤（选填）'
    generator_privacy: '是否公开生成器'
    generator_cover: '生成器封面'
    background_color: '选择背景颜色'
    text_color: '选择文字颜色'
    upload_frame_image: '上传效果框图片'
    upload_example_image: '上传示例底图'
    upload_sticker_image: '上传贴纸图片'
    upload_role_image: '上传角色图片'
    default_quote: '预设名言'
    role_name: '署名'
    upload_basemap_image: '上传底图'
    upload_meme_image: '上傳模因圖'
    default_text: '预设文字'
    top_text: '上方文字（选填）'
    bottom_text: '下方文字'
    delete_this_generator: '删除这个生成器'
    generator_template: '生成器样板'
    user_name: '用户名称'
    user_avatar: '用户头像'
    creator_name: '创作者显示名称'
    multiple_language: '启用多语言'
    choose_multiple_language: '请选择语言'
    yes: '是'
    no: '否'
    image_copyright: '图像来源及版权'
    image_copyright_notice: '图像版权声明及来源链接'
    set_sticker_position: '设定贴纸初始位置'
    align_center: '置中'
    align_left: '置左'
    align_right: '置右'

  message:
    generator_title: '字数限制 30 字，例如：习大大生成器'
    generator_description: '请输入生成器的简短介绍，字数限制 100 字'
    event_information: '请输入相关活动讯息，支援 Markdown 语法'
    tags: '请以空格隔开'
    delete_generator: '生成器删除后无法被復原，删除前请三思'
    delete_success_content: '删掉啦！再也无法復原啦！'
    mobile_save_image_tip: '请在图片上长按以下载图片'
    your_email: '你的Email'
    your_message: '请输入讯息'
    sticker_images: '请上传透明背景之PNG格式图片'
    sticker_example_image: '请上传JPG格式图片，建议尺寸900x600像素'
    avatar_frame_images: '请上传透明背景之PNG格式图片，尺寸为600x600像素'
    avatar_example_image: '请上传JPG格式图片，尺寸为600x600像素'
    cover_frame_images: '请上传透明背景之PNG格式图片，尺寸为850x315像素'
    cover_example_image: '请上传JPG格式图片，尺寸为850x315像素'
    role_images: '请上传JPG或PNG格式图片，尺寸为254x315像素'
    quote_default_text: '请输入名言内容'
    role_name: '请输入名言作者之署名'
    subtitle_basemap_images: '请上传JPG或PNG格式图片，建议尺寸640x480像素'
    subtitle_default_text: '请输入预设设计对白'
    meme_meme_images: '请上传JPG或PNG格式图片'
    meme_top_text: '字数限制 200 字'
    meme_bottom_text: '字数限制 200 字'
    multiple_language: '针对不同语言分别填写标题和简介内容'
    user_photos_warning: '注意：以下图片为您近期使用生成器生成的图片，仅储存于您目前使用的装置，无法跨装置取用'
    user_links_warning: '注意：以下链接为您近期使用生成器生成的链接，仅储存于您目前使用的装置，无法跨装置取用'
    comment_placeholder: '新增公开留言...'
    write_something: '写写心情'
    your_are_human: '你是人类！'
    image_copyright: '您将使用于本生成器之图像素材来源及版权'
    image_copyright_notice: '如图像版权方要求于利用该图片素材需「注明出处」时，请将版权资讯和链接填写于本栏位'
    report_issue: '请帮助我们了解情况'
    comment_message: '字数限制 1000 字'
    sponsor_message: '如果你喜欢我们平台可以用以下方式赞助：'
    poem_text: '仅限中文字，字数限制 10 字'
    inscribed_board_text: '仅限中文字，字数限制 4 字'
    open_in_browser: '请使用浏览器应用开启本页面'

  validation:
    generator_title: '必填，且字数限制为 30 字以内'
    generator_description: '必填，且字数限制为 100 字以内'

  button:
    agree: '同意'
    disagree: '不同意'
    preview_generator: '预览生成器'
    continue_edit: '继续编辑'
    create_generator: '製作生成器'
    create: '完成'
    show_more: '展示更多'
    download_image: '下载图片'
    create_link: '生成链接'
    more_action: '更多'
    previous_step: '上一步'
    next_step: '下一步'
    view_list: '查看列表'
    edit_generator: '编辑'
    delete_generator: '删除生成器'
    update: '保存更改'
    cancel: '取消'
    done: '完成'
    close: '关闭'
    yes_delete: '是的，删了它！'
    send: '发送'
    crop_image: '剪裁'
    filter_effect: '滤镜效果'
    merge_image: '合併到底图'
    choose_image: '上传图片'
    load_my_avatar: '载入头像'
    share_to_feed: '投稿'
    google_login: '以 Google 帐户登入'
    github_login: '以 Github 帐户登入'
    twitter_login: '以 Twitter 帐户登入'
    facebook_login: '以 Facebook 帐户登入'
    use_this_image: '使用这张'
    use_generator: '使用生成器'
    share_to_facebook: '分享到 Facebook'
    share_to_twitter: '分享到 Twitter'
    share_to_googleplus: '分享到 Google+'
    share_to_line: '分享到 Line'
    comment: '留言'
    go_back_feed: '返回动态'
    copy: '复制'
    click_copy: '点击以复制'
    continue: '继续'
    delete_post: '删除这篇发文'
    report: '举报'
    generate_poem: '生成诗文'

  alert:
    generator_title_empty: '请填写生成器名称'
    generator_description_empty: '请填写生成器简介'
    generator_cover_empty: '请上传封面图片'
    frame_image_empty: '请上传相框图片'
    example_image_empty: '请上传示例图片'
    sticker_image_empty: '请上传贴纸图片'
    basemap_image_empty: '请上传底图'
    default_text_empty: '请输入预设文字'
    role_image_empty: '请上传角色图片'
    role_name_empty: '请输入署名'
    generator_create_failed: '生成器创建失败，请稍后再试'
    merge_success: '合上去啦！'
    verify_failed: '验证失败，请稍后再试'
    setting_updated: '谢谢，你的设定已储存。'
    something_went_wrong: '糟糕，出错了！请尝试重新整理或稍后再试'
    local_preview_failed: '图片预览载入失败！'
    image_upload_failed: '图片上传失败，请稍后再试'
    link_generating: '图片链接生成中，请稍候⋯⋯'
    link_generate_failed: '糟糕！图片链接生成失败，请稍后再试'
    login_failed: '登入失败，请尝试重新整理或稍后再试'
    logout_failed: '登出失败，请尝试重新整理或稍后再试'
    list_loading_failed: '列表载入失败，请尝试重新整理'
    no_more_data: '最后一页了'
    delete_success: '删除成功！'
    delete_failed: '糟糕！删除失败，请稍后再试！'
    processing: '处理中，请稍候⋯⋯'
    report_success: '感谢您的举报'

  user_terms:
    title: '使用者条款'
    content: '使用者条款内容'

  time:
    years_ago: '年前'
    months_ago: '个月前'
    days_ago: '天前'
    hours_ago: '小时前'
    mins_ago: '分钟前'
    just_now: '現在'

  tooltip:
    set_as_default: '设为预设'
    crop_image: '裁切图片'
    remove_item: '移除'

  report:
    reason_1: '我就是不喜欢'
    reason_2: '对我或我认识的人造成骚扰'
    reason_3: '我认为它不应出现在 gengen.co'
    reason_4: '诈骗信息'
    reason_5: '未经我授权便使用了我的知识产权'
    reason_6: '其他（请说明）'
